spring:
  profiles:
    active: "development"

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://mysql.broccoliapp.io:3306/broccoli2?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: bro
    password: WUxZEFTxWG8oIeGy23qc!
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1
  jpa:
      hibernate:
        ddl-auto: create
        show_sql: true
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://mysql.broccoliapp.io:3306/broccoli?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: bro
    password: WUxZEFTxWG8oIeGy23qc!
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
      hibernate:
        ddl-auto: create
        show_sql: false
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false