spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api
    driver-class-name: com.mysql.jdbc.Driver
    username: api
    password: api
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
